version: '2'

services:
  pio_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=predictionio
      - POSTGRES_PASSWORD=1234

  elasticsearch:
    image: elasticsearch:1.7.6
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - ./files/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=pio
      - http.host=0.0.0.0
      - network.publish_host=127.0.0.1
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  pio:
    build: .
    image: predictionio
    depends_on:
    - pio_db
    - elasticsearch
    volumes:
    - ./files/pio-env.sh:/opt/pio/conf/pio-env.sh:ro
    ports:
    - 8000:8000
    - 7070:7070
